functionsDirectory = "D:\\stand\\netlify\\functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[dev]
  command = "npm run dev"
  targetPort = 3001
  port = 8888


[build]
publish = "D:\\stand\\dist"
publishOrigin = "config"
commandOrigin = "ui"
command = "npm run build"
functions = "D:\\stand\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]